### ISSUE TITLE
Initial population of the database (part 2)

### ISSUE THREAD

**Issue by imilne** [cropgeeks/cranachan#4]
Gene information.

**Comment by LindaMilne** [comment]
The data is in the form of GFF files. Created by using GMAP to find the areas of the pseudomolecules which most closely match the genes. This was done for the MLOC, JLOC1 JLOC2 and HORVU gene sets. For any gene there can be more than one location (including a few of the HORVUs). Files are in ....projects/barley/201710_cranachan.

889336860 Nov 21 13:42 gmap_chr_HORVU_genes_gbrowsetrack.gff
132451615 Nov 21 13:34 gmap_chr_JLOC1_genes_gbrowsetrack.gff
185160582 Nov 21 13:35 gmap_chr_JLOC2_genes_try5_gbrowsetrack.gff
239229753 Nov 21 13:35 gmap_chr_MLOC_genes_try5_gbrowsetrack.gff
